# Generated by Django 5.1.3 on 2025-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_appointment_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
